"""Rename transaction date column name

Revision ID: e5934d50edf3
Revises: c5ee3ac69981
Create Date: 2025-01-22 19:51:14.974990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5934d50edf3'
down_revision: Union[str, None] = 'c5ee3ac69981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'budgets', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.add_column('transactions', sa.Column('transaction_date', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.drop_column('transactions', 'date')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('transactions', sa.Column('date', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'transaction_date')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'budgets', type_='unique')
    # ### end Alembic commands ###
